version: '3.8'

services:
    web:
        build: .
        container_name: django_app
        ports:
        - "8000:8000"
        volumes:
        - .:/app
        depends_on:
        - db
    db:
        image: postgres:13
        container_name: postgres_db
        restart: always
        environment:
          POSTGRES_DB: portfolio
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        ports:
          - "5432:5432"