name: Deploy Django App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get GitHub Actions IP
        run: |
          echo "Fetching GitHub Actions public IP..."
          PUBLIC_IP=$(curl -s https://api64.ipify.org)
          echo "GitHub Actions IP: $PUBLIC_IP"
          
          echo "Updating AWS Security Group..."
          aws ec2 authorize-security-group-ingress --group-id ${{ secrets.AWS_SECURITY_GROUP_ID }} --protocol tcp --port 22 --cidr $PUBLIC_IP/32


      - name: Setup SSH
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > deploy_key
          chmod 600 deploy_key
          ssh -i deploy_key -o StrictHostKeyChecking=no ubuntu@13.60.241.10
          cd portfolio
          git pull origin main
          docker-compose up --build -d
          exit
          rm -f deploy_key