name: Deploy Django App to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1
      - name : Debug SSM Command Execution
        run : |
          echo "Fetching latest SSM command..."
          COMMAND_ID=$(aws ssm list-commands --query "Commands[0].CommandId" --output text)

          echo "Command ID: $COMMAND_ID"

          echo "Fetching detailed invocation log..."
          aws ssm get-command-invocation --command-id $COMMAND_ID --instance-id ${{ secrets.EC2_INSTANCE_ID }}
        env :
          AWS_ACCESS_KEY_ID : ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY : ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION : eu-north-1
      - name: Deploy application via AWS SSM
        run: |
          COMMAND_ID=$(aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets '[{"Key":"InstanceIds","Values":["${{ secrets.EC2_INSTANCE_ID }}"]}]' \
            --parameters '{"commands":[
              "if [ ! -d ~/portfolio/.git ]; then rm -rf ~/portfolio && git clone https://github.com/Mateusz-Strz/portfolio_dj.git ~/portfolio; fi",
              "cd ~/portfolio",
              "git pull origin main",
              "docker-compose down",
              "docker-compose up --build -d"
            ]}'


          aws ssm wait command-executed \
            --command-id "$COMMAND_ID" \
            --instance-id "${{ secrets.EC2_INSTANCE_ID }}"


